import { useCallback, useEffect, useRef, useState } from 'react'
import Icon from '../components/Icon.jsx'
import photos from 'virtual:gallery'

// `virtual:gallery` is generated by the gallery-manifest plugin in
// vite.config.js: every image in src/assets/gallery/ with its intrinsic
// dimensions and downscaled WebP renditions attached. Drop a file into that
// folder and it appears here.

const srcSetOf = (photo) =>
  photo.variants.map((v) => `${v.src} ${v.width}w`).join(', ') || undefined

// Thumbnails track the gallery's column count; the breakpoints mirror styles.css.
const GRID_SIZES = '(max-width: 720px) 50vw, (max-width: 1100px) 33vw, 25vw'

export default function Photography() {
  const [active, setActive] = useState(null)
  const isOpen = active !== null

  const close = useCallback(() => setActive(null), [])
  const next = useCallback(
    () => setActive((i) => (i + 1) % photos.length),
    [],
  )
  const prev = useCallback(
    () => setActive((i) => (i - 1 + photos.length) % photos.length),
    [],
  )

  const dialogRef = useRef(null)
  const closeRef = useRef(null)
  // Remembers which thumbnail opened the lightbox so focus can go back to it.
  const openerRef = useRef(null)

  useEffect(() => {
    if (!isOpen) return

    const onKey = (e) => {
      if (e.key === 'Escape') return close()
      if (e.key === 'ArrowRight') return next()
      if (e.key === 'ArrowLeft') return prev()
      if (e.key !== 'Tab') return

      // Keep Tab inside the dialog; without this, focus walks the page behind it.
      const focusable = dialogRef.current?.querySelectorAll('button')
      if (!focusable?.length) return
      const first = focusable[0]
      const last = focusable[focusable.length - 1]
      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault()
        last.focus()
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault()
        first.focus()
      }
    }

    window.addEventListener('keydown', onKey)
    // Prevent the page behind the lightbox from scrolling.
    const prevOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    closeRef.current?.focus()

    return () => {
      window.removeEventListener('keydown', onKey)
      document.body.style.overflow = prevOverflow
      openerRef.current?.focus()
    }
  }, [isOpen, close, next, prev])

  return (
    <>
      <div className="page-head">
        <h1 className="page-title">Photography</h1>
        <p className="page-subtitle">A selection of photographs.</p>
        <a
          className="insta-link"
          href="https://instagram.com/dobbypic"
          target="_blank"
          rel="noreferrer"
        >
          <Icon name="instagram" size={18} />
          <span>@dobbypic</span>
        </a>
      </div>

      {photos.length === 0 ? (
        <p className="empty-note">
          No photos yet. Drop images into <code>src/assets/gallery/</code> to
          populate this gallery.
        </p>
      ) : (
        <ul className="gallery">
          {photos.map((photo, i) => (
            <li key={photo.src} className="gallery-item">
              <button
                type="button"
                className="gallery-button"
                onClick={(e) => {
                  openerRef.current = e.currentTarget
                  setActive(i)
                }}
                aria-label={`Open photograph ${i + 1} of ${photos.length}`}
                aria-haspopup="dialog"
              >
                {/* Filenames carry no meaning, so the images are decorative and
                    the button label is what assistive tech announces. */}
                <picture>
                  <source
                    type="image/webp"
                    srcSet={srcSetOf(photo)}
                    sizes={GRID_SIZES}
                  />
                  <img
                    src={photo.src}
                    alt=""
                    width={photo.width ?? undefined}
                    height={photo.height ?? undefined}
                    loading="lazy"
                    decoding="async"
                  />
                </picture>
              </button>
            </li>
          ))}
        </ul>
      )}

      {isOpen && (
        <div
          className="lightbox"
          ref={dialogRef}
          role="dialog"
          aria-modal="true"
          aria-label={`Photograph ${active + 1} of ${photos.length}`}
          onClick={close}
        >
          <button
            ref={closeRef}
            type="button"
            className="lightbox-close"
            aria-label="Close"
            onClick={close}
          >
            ×
          </button>
          <button
            type="button"
            className="lightbox-nav prev"
            aria-label="Previous photograph"
            onClick={(e) => {
              e.stopPropagation()
              prev()
            }}
          >
            ‹
          </button>
          <picture onClick={(e) => e.stopPropagation()}>
            <source
              type="image/webp"
              srcSet={srcSetOf(photos[active])}
              sizes="92vw"
            />
            <img
              className="lightbox-img"
              src={photos[active].src}
              alt=""
              width={photos[active].width ?? undefined}
              height={photos[active].height ?? undefined}
            />
          </picture>
          <button
            type="button"
            className="lightbox-nav next"
            aria-label="Next photograph"
            onClick={(e) => {
              e.stopPropagation()
              next()
            }}
          >
            ›
          </button>
        </div>
      )}
    </>
  )
}
